### PR TITLE
Replace deprecated packages.

### PR DESCRIPTION
**Pull request by menelaos**
* Replace `system-filepath` with `filepath`
* Replace `system-fileio` with `directory`
* Fix typos and indentation

### CODE REVIEW

**Comment by jfischoff** [comment]
I failures look pretty easy to fix. I think you still need to import Control.Applicative ((<$>)) for pre-AMP version of GHC. 

Otherwise looks great, thanks a lot :)

**Comment by jfischoff** [comment]
Thanks. I've added you to the list of collaborators.

**Comment by jfischoff** [comment]
If you have a hackage user name I will add you as a maintainer too.

**Comment by menelaos** [comment]
Thanks, my hackage user name is `AndreasSchacker`.

**Comment by jfischoff** [comment]
Done. Thanks again.

**Pull request merged**
